server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://47.106.174.156:8761/eureka/,http://47.106.174.156:8762/eureka/
spring:
  application:
    name: eureka-client-A
zuul:
  routes:
    eureka-client-B:
      path: /CB/**
      serviceId: eureka-client-B